# -*- coding: utf-8 -*-
"""Smart AI Song Recommendation System Using Word Embedding

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VYW9TXIpL2CM_ImnJQp9GCwFPNtd-Kkx

Install Required Packages
"""

# Install required packages

!pip install gensim nltk --quiet

"""gensim → Used to train the Word2Vec model.

nltk → Used for text preprocessing such as tokenization and stopword removal.

Import Required Libraries
"""

# Data manipulation
import pandas as pd
import numpy as np

# Regular expressions
import re

# Natural Language Toolkit
import nltk

# Download required NLTK resources
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

# Tokenization and stopwords
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# Word Embedding
from gensim.models import Word2Vec

# Similarity calculation
from sklearn.metrics.pairwise import cosine_similarity

# Save and load models
import pickle

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

"""| Library           | Purpose                                     |
| ----------------- | ------------------------------------------- |
| pandas            | Load and manipulate datasets                |
| numpy             | Numerical computations                      |
| re                | Clean text using regular expressions        |
| nltk              | NLP preprocessing                           |
| word_tokenize     | Split lyrics into words                     |
| stopwords         | Remove common words like "is", "the", "and" |
| Word2Vec          | Learn word embeddings                       |
| cosine_similarity | Measure similarity between songs            |
| pickle            | Save trained objects for later use          |
| warnings          | Hide unnecessary warning messages           |

Verify Installation
"""

print("All libraries imported successfully!")

"""| Stage                  | Library Used      |
| ---------------------- | ----------------- |
| Load CSV Dataset       | pandas            |
| Text Cleaning          | re                |
| Remove Stopwords       | nltk              |
| Tokenization           | nltk              |
| Train Word2Vec         | gensim            |
| Create Song Embeddings | numpy             |
| Compare Songs          | cosine_similarity |
| Save Model             | pickle            |

Load Dataset
"""

# Load dataset

df = pd.read_csv("lyrics.csv")

"""Display First 5 Records"""

df.head()

"""Remove Unnecessary Column"""

# Remove index column

df = df.drop("Unnamed: 0", axis=1)

"""Display Columns"""

df.columns

"""Check Dataset Shape"""

df.shape

"""Dataset Information"""

df.info()

"""Check Missing Values"""

df.isnull().sum()

"""Remove Missing Values"""

df = df.dropna()

"""Check Duplicate Records"""

df.duplicated().sum()

"""Remove Duplicate Records"""

df = df.drop_duplicates()

"""Verify Dataset Shape"""

df.shape

"""Display Random Songs"""

df.sample(5)

"""Top 10 Artists"""

df["artist"].value_counts().head(10)

"""Number of Unique Artists"""

df["artist"].nunique()

"""Song Length"""

df["lyric_length"] = df["lyrics"].str.len()

df[["song_name","artist","lyric_length"]].head()

"""Longest Songs"""

df[["song_name","artist","lyric_length"]].sort_values(
    by="lyric_length",
    ascending=False
).head(10)

"""Dataset Workflow

lyrics.csv
      │
      ▼
Load Dataset
      │
      ▼
Remove Index Column
      │
      ▼
Check Shape
      │
      ▼
Check Missing Values
      │
      ▼
Remove Missing Values
      │
      ▼
Remove Duplicate Records
      │
      ▼
Explore Artists & Songs
      │
      ▼
Ready for Text Preprocessing

Text Preprocessing

song lyrics so that the Word2Vec model learns meaningful word relationships instead of punctuation, numbers, and unnecessary words.

After preprocessing, each song lyric will become a list of important words.

Raw Lyrics
     │
     ▼
Convert to Lowercase
     │
     ▼
Remove [Chorus], [Verse], etc.
     │
     ▼
Remove URLs
     │
     ▼
Remove Numbers
     │
     ▼
Remove Punctuation
     │
     ▼
Remove Extra Spaces
     │
     ▼
Tokenization
     │
     ▼
Remove Stopwords
     │
     ▼
Cleaned Tokens

Create Stopword List
"""

# English stopwords

stop_words = set(stopwords.words('english'))

"""the
is
am
are
was
were
of
and
to
in

These words will be removed.

Create Text Cleaning Function
"""

import string

def clean_text(text):

    # Convert to lowercase
    text = text.lower()

    # Remove text inside square brackets
    text = re.sub(r'\[.*?\]', ' ', text)

    # Remove URLs
    text = re.sub(r'http\S+|www\S+', ' ', text)

    # Remove numbers
    text = re.sub(r'\d+', ' ', text)

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

"""Convert text to lowercase

Remove [Verse], [Chorus]

Remove URLs

Remove numbers

Remove punctuation

Remove extra spaces

Apply Cleaning Function
"""

# Create cleaned lyrics column

df["clean_lyrics"] = df["lyrics"].apply(clean_text)

"""View Results"""

df[["lyrics","clean_lyrics"]].head()

import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

"""Tokenization"""

# Split lyrics into words

df["tokens"] = df["clean_lyrics"].apply(word_tokenize)

"""Remove Stopwords"""

def remove_stopwords(words):

    return [
        word
        for word in words
        if word not in stop_words
        and len(word) > 2
    ]

"""Apply Stopword Removal"""

df["tokens"] = df["tokens"].apply(remove_stopwords)

"""Before

['i','love','the','music','and','dance']

↓

After

['love','music','dance']

Display Clean Tokens
"""

df[["song_name","tokens"]].head()

"""Check Empty Lyrics"""

df["tokens"].apply(len).describe()

"""Remove Empty Songs"""

df = df[df["tokens"].apply(len) > 0]

"""Reset Index"""

df.reset_index(drop=True, inplace=True)

"""Verify Dataset"""

df[["artist","song_name","tokens"]].sample(5)

"""Save the Preprocessed Dataset"""

# Save cleaned dataset

df.to_csv("cleaned_lyrics.csv", index=False)

print("Cleaned dataset saved successfully!")

"""lyrics.csv
      │
      ▼
Load Dataset
      │
      ▼
Clean Text
      │
      ▼
Tokenization
      │
      ▼
Stopword Removal
      │
      ▼
Clean Tokens
      │
      ▼
Ready for Word2Vec Training

DataFrame will contain

| Column       | Description             |
| ------------ | ----------------------- |
| artist       | Artist name             |
| song_name    | Song title              |
| lyrics       | Original lyrics         |
| clean_lyrics | Cleaned lyrics text     |
| tokens       | List of processed words |

Cleaned Song Lyrics (Tokens)
           │
           ▼
Train Word2Vec Model
           │
           ▼
Learn Word Vectors
           │
           ▼
Build Vocabulary
           │
           ▼
Find Similar Words
           │
           ▼
Save Trained Model

Check the Tokenized Data
"""

# Display tokenized lyrics

df[["song_name", "tokens"]].head()

"""Train the Word2Vec Model"""

from gensim.models import Word2Vec

# Train Word2Vec model

word2vec_model = Word2Vec(
    sentences=df["tokens"],
    vector_size=100,
    window=5,
    min_count=2,
    workers=4,
    sg=1
)

"""| Parameter   | Value        | Description                                                        |
| ----------- | ------------ | ------------------------------------------------------------------ |
| sentences   | df["tokens"] | Tokenized lyrics                                                   |
| vector_size | 100          | Each word is represented by a 100-dimensional vector               |
| window      | 5            | Considers 5 words before and after the current word                |
| min_count   | 2            | Ignores words appearing only once                                  |
| workers     | 4            | Uses 4 CPU cores for faster training                               |
| sg          | 1            | Uses the **Skip-Gram** model (recommended for semantic similarity) |

Check Vocabulary Size
"""

# Total number of unique words learned

print("Vocabulary Size:", len(word2vec_model.wv.index_to_key))

"""Display First 20 Words in Vocabulary"""

# Display first 20 words

word2vec_model.wv.index_to_key[:20]

"""Display First 20 Words in Vocabulary"""

# Display first 20 words

word2vec_model.wv.index_to_key[:20]

"""Check Whether a Word Exists"""

word = "love"

if word in word2vec_model.wv:
    print(f"'{word}' is available in the vocabulary.")
else:
    print(f"'{word}' is not available.")

"""View Word Vector"""

# Display vector for the word "love"

word2vec_model.wv["love"]

"""Check Vector Shape"""

print(word2vec_model.wv["love"].shape)

"""The output (100,) indicates that the word is represented as a 100-dimensional vector. This is because the Word2Vec model was trained with vector_size=100, meaning each word is encoded using 100 numerical features that capture its semantic meaning.

====

Word
  │
  ▼
Word2Vec Model
  │
  ▼
100 Numerical Values
  │
  ▼
(100,)

=====

This means each word is represented using 100 numerical features.

Find Similar Words
"""

word2vec_model.wv.most_similar("love", topn=10)

"""Calculate Similarity Between Two Words"""

similarity = word2vec_model.wv.similarity("love", "heart")

print("Similarity Score:", similarity)

""""love" and "heart" are highly related words

====


The similarity score is calculated using Cosine Similarity between the vector of "love" and the vector of "heart".

The score ranges from -1 to 1.

=====

| Similarity Score | Meaning                     |
| ---------------- | --------------------------- |
| 1.00             | Exactly the same meaning    |
| 0.80 – 0.99      | Very highly similar         |
| 0.60 – 0.79      | Highly similar              |
| 0.40 – 0.59      | Moderately similar          |
| 0.20 – 0.39      | Slightly similar            |
| 0.00             | No semantic similarity      |
| Negative         | Opposite semantic direction |

Visualization using PCA
"""

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Words to visualize
words = [
    "love", "heart", "baby", "kiss",
    "music", "dance", "dream", "night",
    "life", "world"
]

# Keep only words that exist in the vocabulary
words = [word for word in words if word in word2vec_model.wv]

# Get word vectors
vectors = [word2vec_model.wv[word] for word in words]

# Reduce dimensions from 100 -> 2
pca = PCA(n_components=2)
result = pca.fit_transform(vectors)

# Plot
plt.figure(figsize=(8,6))

for i, word in enumerate(words):
    plt.scatter(result[i,0], result[i,1], s=80)
    plt.text(result[i,0]+0.01, result[i,1]+0.01, word, fontsize=11)

plt.title("Word2Vec Word Embeddings (PCA)")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.grid(True)

plt.show()

"""Visualization using t-SNE"""

import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
import numpy as np # Import numpy

words = [
    "love", "heart", "baby", "kiss",
    "music", "dance", "dream", "night",
    "life", "world"
]

words = [w for w in words if w in word2vec_model.wv]

vectors = [word2vec_model.wv[w] for w in words]

# Convert list of vectors to a single NumPy array
vectors_array = np.array(vectors)

tsne = TSNE(
    n_components=2,
    random_state=42,
    perplexity=5
)

result = tsne.fit_transform(vectors_array)

plt.figure(figsize=(8,6))

for i, word in enumerate(words):
    plt.scatter(result[i,0], result[i,1], s=80)
    plt.text(result[i,0]+0.3, result[i,1]+0.3, word, fontsize=11)

plt.title("Word2Vec Embeddings using t-SNE")
plt.grid(True)

plt.show()

"""Visualizing the Relationship Between "love" and "heart"
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))

x = [0, 1]
y = [0, 0.6]

plt.scatter(x, y, s=150)

plt.text(x[0], y[0], "love", fontsize=12)
plt.text(x[1], y[1], "heart", fontsize=12)

plt.plot(x, y, '--')

plt.title("Semantic Relationship Between 'love' and 'heart'")
plt.xlim(-0.5, 1.5)
plt.ylim(-0.5, 1.2)

plt.grid(True)
plt.show()

"""| **Feature**                        | **PCA**                                             | **t-SNE**                                             |
| ---------------------------------- | --------------------------------------------------- | ----------------------------------------------------- |
| **Full Form**                      | Principal Component Analysis                        | t-distributed Stochastic Neighbor Embedding           |
| **Type**                           | Linear Dimensionality Reduction                     | Non-linear Dimensionality Reduction                   |
| **Purpose**                        | Reduce dimensions while preserving maximum variance | Reduce dimensions while preserving local similarities |
| **Developed For**                  | Feature reduction and visualization                 | Data visualization and clustering                     |
| **Works On**                       | Linear relationships                                | Non-linear relationships                              |
| **Output Dimensions**              | 2D or 3D                                            | 2D or 3D                                              |
| **Speed**                          | Fast                                                | Slow                                                  |
| **Computational Cost**             | Low                                                 | High                                                  |
| **Cluster Visualization**          | Moderate                                            | Excellent                                             |
| **Preserves Variance**             | ✅ Yes                                               | ❌ No                                                  |
| **Preserves Local Structure**      | Limited                                             | ✅ Excellent                                           |
| **Suitable for Large Datasets**    | ✅ Yes                                               | Limited                                               |
| **Interpretability**               | Easy                                                | Moderate                                              |
| **Feature Reduction**              | ✅ Yes                                               | ❌ No                                                  |
| **Visualization**                  | ✅ Yes                                               | ✅ Yes                                                 |
| **Word2Vec Visualization**         | Good                                                | Best                                                  |
| **BERT Embedding Visualization**   | Good                                                | Best                                                  |
| **Machine Learning Preprocessing** | ✅ Yes                                               | ❌ No                                                  |

**Create Song Embeddings**

we will convert each song into one numerical vector.

Since Word2Vec creates vectors only for individual words, we need to combine all the word vectors of a song into a single Song Embedding.

Later, we will compare these song embeddings to recommend similar songs.

====

Song Lyrics
      │
      ▼
Tokenized Words
      │
      ▼
Get Word2Vec Vector
for Each Word
      │
      ▼
Average All Word Vectors
      │
      ▼
One Song Embedding
(100 Dimensions)
      │
      ▼
Store for Every Song

**Create Function to Generate Song Embedding**
"""

import numpy as np

def get_song_embedding(tokens, model):

    vectors = []

    for word in tokens:

        if word in model.wv:
            vectors.append(model.wv[word])

    if len(vectors) == 0:
        return np.zeros(model.vector_size)

    return np.mean(vectors, axis=0)

"""Reads every word in a song

Finds its Word2Vec vector

Stores all vectors

Calculates the average

Returns one vector for the entire song

Create Song Embeddings
"""

df["song_embedding"] = df["tokens"].apply(
    lambda x: get_song_embedding(x, word2vec_model)
)

"""Creates a new column

song_embedding

Every row now contains one vector.

View the Result
"""

df[["song_name","song_embedding"]].head()

"""Check Embedding Shape"""

print(df["song_embedding"][0].shape)

"""Each song is represented by

100 numerical values

Display First 10 Values
"""

df["song_embedding"][0][:10]

"""| Observation         | Meaning                                                               |
| ------------------- | --------------------------------------------------------------------- |
| `song_embedding`    | A new column containing the vector representation of each song.       |
| `[0]`               | Selects the **first song** in the dataset.                            |
| `[:10]`             | Displays only the **first 10 values** of the song's embedding vector. |
| `-0.12981223`       | First feature of the song vector (learned by Word2Vec).               |
| `0.27438867`        | Second feature of the song vector.                                    |
| `0.41597462`        | Third feature of the song vector.                                     |
| `dtype=float32`     | Each value is stored as a 32-bit floating-point number.               |
| Total Vector Length | **100 values** (because `vector_size=100`).                           |

=====

| Value        | Meaning                                                                            |
| ------------ | ---------------------------------------------------------------------------------- |
| Positive (+) | Indicates the feature contributes in one direction in the learned embedding space. |
| Negative (-) | Indicates the feature contributes in the opposite direction.                       |
| Zero (0)     | Very little contribution for that feature.                                         |


=====
What Does Each Number Represent?


| Feature Number | Value    | Meaning             |
| -------------- | -------- | ------------------- |
| Feature 1      | -0.1298  | Learned feature 1   |
| Feature 2      | 0.2743   | Learned feature 2   |
| Feature 3      | 0.4160   | Learned feature 3   |
| Feature 4      | 0.0653   | Learned feature 4   |
| ...            | ...      | ...                 |
| Feature 100    | (hidden) | Learned feature 100 |

These are latent features discovered by the Word2Vec algorithm from the training data.

=====

Why Do We Need This Vector?

Instead of comparing song lyrics word by word, we compare these vectors.

| Song   | Embedding                  |
| ------ | -------------------------- |
| Song A | `[0.21, -0.45, 0.18, ...]` |
| Song B | `[0.19, -0.41, 0.22, ...]` |

Then we calculate:

cosine_similarity(songA_vector, songB_vector)

If the similarity is high, the songs are recommended as similar.

Song Lyrics
      │
      ▼
Word2Vec
      │
      ▼
Word Vectors
      │
      ▼
Average All Word Vectors
      │
      ▼
Song Embedding (100 values)
      │
      ▼
Compare Songs Using Cosine Similarity

**Verify All Songs Have Embeddings**
"""

len(df["song_embedding"])

"""All songs now have embeddings.

Create Embedding Matrix
"""

song_embeddings = np.vstack(df["song_embedding"].values)

print(song_embeddings.shape)

"""25005 songs
100 features for each song

Save Embedding Matrix
"""

import pickle

pickle.dump(
    song_embeddings,
    open("song_embeddings.pkl", "wb")
)

print("Song embeddings saved successfully!")

"""Save Processed Dataset"""

df.to_pickle("songs_dataframe.pkl")

print("Dataset saved successfully!")

"""| Step                             | Status |
| -------------------------------- | ------ |
| Created Song Embedding Function  | ✅      |
| Converted Every Song into Vector | ✅      |
| Checked Embedding Shape          | ✅      |
| Created Embedding Matrix         | ✅      |
| Saved Embeddings                 | ✅      |
| Saved Dataset                    | ✅      |

| File                        | Purpose                |
| --------------------------- | ---------------------- |
| `word2vec_song_model.model` | Trained Word2Vec model |
| `song_embeddings.pkl`       | Song vectors           |
| `songs_dataframe.pkl`       | Processed dataset      |

Song Name
     │
     ▼
Find Song Embedding
     │
     ▼
Compare with All Song Embeddings
(Cosine Similarity)
     │
     ▼
Similarity Scores
     │
     ▼
Sort Scores
     │
     ▼
Top 5 Similar Songs
     │
     ▼
Display Recommendations

Import Cosine Similarity

cosine_similarity() measures how similar two song embeddings are.
"""

from sklearn.metrics.pairwise import cosine_similarity

"""Calculate Similarity Matrix"""

# Calculate similarity between every pair of songs

similarity_matrix = cosine_similarity(song_embeddings)

print("Similarity Matrix Shape:", similarity_matrix.shape)

"""| Value         | Meaning                              |
| ------------- | ------------------------------------ |
| 25005 Rows    | Each row represents one song         |
| 25005 Columns | Each column represents one song      |
| Cell (i,j)    | Similarity between Song i and Song j |

View Similarity Matrix
"""

similarity_matrix

"""| Observation               | Meaning                                                                                      |
| ------------------------- | -------------------------------------------------------------------------------------------- |
| `similarity_matrix`       | A matrix containing similarity scores between all songs.                                     |
| Shape `(25742, 25742)`    | There are **25,742 songs**, so the matrix has 25,742 rows and 25,742 columns.                |
| Each **row**              | Represents one reference song.                                                               |
| Each **column**           | Represents another song being compared.                                                      |
| `similarity_matrix[i][j]` | Similarity score between Song **i** and Song **j**.                                          |
| Value Range               | Scores range from **-1 to 1**, but for song embeddings they are usually between **0 and 1**. |
| Value `1.0`               | A song compared with itself (100% similar).                                                  |
| Value close to `1`        | Songs are very similar.                                                                      |
| Value close to `0`        | Songs are very different.                                                                    |


====

| Compared With |    Song A |    Song B |    Song C |    Song D |    Song E |
| ------------- | --------: | --------: | --------: | --------: | --------: |
| **Song A**    | **1.000** |     0.936 |     0.966 |     0.937 |     0.949 |
| **Song B**    |     0.936 | **1.000** |     0.937 |     0.920 |     0.938 |
| **Song C**    |     0.966 |     0.937 | **1.000** |     0.933 |     0.953 |
| **Song D**    |     0.937 |     0.920 |     0.933 | **1.000** |     0.949 |
| **Song E**    |     0.949 |     0.938 |     0.953 |     0.949 | **1.000** |


===

|     Value | Meaning                                   |
| --------: | ----------------------------------------- |
| **1.000** | Same song compared with itself.           |
| **0.966** | Song A and Song C are highly similar.     |
| **0.949** | Song A and Song E are very similar.       |
| **0.936** | Song A and Song B are similar.            |
| **0.920** | Song B and Song D are moderately similar. |


===

Why is the Diagonal Always 1?

         Song A   Song B   Song C

Song A    1.0
Song B             1.0
Song C                      1.0


A song is always 100% similar to itself, so every diagonal element is 1.0.

========

Song Embeddings
       │
       ▼
Cosine Similarity
       │
       ▼
Similarity Matrix
       │
       ▼
Compare Every Song
with Every Other Song
       │
       ▼
Recommend Most Similar Songs

Create Recommendation Function
"""

def recommend_songs(song_name, top_n=5):

    # Check if song exists
    if song_name not in df["song_name"].values:
        return "Song not found!"

    # Get index of the selected song
    idx = df[df["song_name"] == song_name].index[0]

    # Get similarity scores
    scores = list(enumerate(similarity_matrix[idx]))

    # Sort scores in descending order
    scores = sorted(scores, key=lambda x: x[1], reverse=True)

    # Remove the selected song itself
    scores = scores[1:top_n+1]

    recommendations = []

    for index, score in scores:

        recommendations.append({
            "Song": df.iloc[index]["song_name"],
            "Artist": df.iloc[index]["artist"],
            "Similarity": round(score, 3)
        })

    return pd.DataFrame(recommendations)

"""Finds the selected song.
Retrieves its embedding.
Compares it with all other songs.
Sorts by similarity.
Returns the Top 5 recommendations.

Test the Recommendation System
"""

recommend_songs("Believe")

recommend_songs("Hello")

recommend_songs("Imagine")

recommend_songs("Love")

"""Check if a Song Exists

This lists songs containing the word love.
"""

df[df["song_name"].str.contains("love", case=False)][["song_name", "artist"]].head(20)

"""Test Multiple Songs"""

recommend_songs("Mamma Mia")

recommend_songs("Dancing Queen")

recommend_songs("Hello")

"""| Step                          | Status |
| ----------------------------- | ------ |
| Imported Cosine Similarity    | ✅      |
| Created Similarity Matrix     | ✅      |
| Built Recommendation Function | ✅      |
| Tested Recommendations        | ✅      |

"""

# Define idx for a specific song, for example, 'Believe'
song_name_to_test = "Believe"
if song_name_to_test in df["song_name"].values:
    idx = df[df["song_name"] == song_name_to_test].index[0]
    scores = cosine_similarity(
        [song_embeddings[idx]],
        song_embeddings
    )[0]
    print(f"Similarity scores for '{song_name_to_test}' calculated.")
else:
    print(f"Song '{song_name_to_test}' not found in the dataset.")

"""Sort Similarity Scores"""

# Pair each song index with its similarity score
similarity_scores = list(enumerate(scores))

# Sort in descending order
similarity_scores = sorted(
    similarity_scores,
    key=lambda x: x[1],
    reverse=True
)

"""| Code                | Purpose                                                   |
| ------------------- | --------------------------------------------------------- |
| `enumerate(scores)` | Adds the song index to each similarity score.             |
| `sorted()`          | Sorts songs from highest similarity to lowest similarity. |
| `reverse=True`      | Displays the most similar songs first.                    |

Display Top 5 Songs
"""

print("Top 5 Recommended Songs\n")

count = 0

for index, score in similarity_scores:

    # Skip the same song
    if df.iloc[index]["song_name"] == song_name_to_test:
        continue

    print(f"Song       : {df.iloc[index]['song_name']}")
    print(f"Artist     : {df.iloc[index]['artist']}")
    print(f"Similarity : {score:.4f}")
    print("-"*40)

    count += 1

    if count == 5:
        break

"""Selected Song
      │
      ▼
Calculate Similarity
      │
      ▼
Sort Similarity Scores
      │
      ▼
Skip Selected Song
      │
      ▼
Top 5 Similar Songs
      │
      ▼
Display Recommendations

=====

| Observation    | Meaning                                                               |
| -------------- | --------------------------------------------------------------------- |
| `scores`       | Similarity score of the selected song with every song in the dataset. |
| `enumerate()`  | Stores the song index along with its similarity score.                |
| `sorted()`     | Arranges songs from highest to lowest similarity.                     |
| `reverse=True` | Ensures the most similar songs appear first.                          |
| `continue`     | Skips the selected song because it is always 100% similar to itself.  |
| `count == 5`   | Stops after displaying the top 5 recommendations.                     |

Install Gradio

Gradio is used to build an interactive web interface with just a few lines of Python.
"""

!pip install gradio --quiet

"""Import Libraries"""

import gradio as gr
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

"""Create Recommendation Function

| Code              | Purpose                          |
| ----------------- | -------------------------------- |
| Check song exists | Avoid invalid input              |
| Find index        | Locate the selected song         |
| Cosine similarity | Compare with all songs           |
| Sort scores       | Highest similarity first         |
| Skip current song | Do not recommend the same song   |
| Return Top 5      | Display the best recommendations |
"""

def recommend_song(song_name):

    # Remove extra spaces and convert to lowercase
    song_name = song_name.strip().lower()

    # Create lowercase song names
    song_names = df["song_name"].str.lower()

    # Check if song exists
    if song_name not in song_names.values:
        return "❌ Song not found in the dataset."

    # Get index
    idx = song_names[song_names == song_name].index[0]

    # Calculate similarity
    similarity_scores = cosine_similarity(
        [song_embeddings[idx]],
        song_embeddings
    )[0]

    # Sort
    similar_indices = similarity_scores.argsort()[::-1]

    recommendations = []

    for i in similar_indices:

        if i == idx:
            continue

        recommendations.append(
            f"{df.iloc[i]['song_name']} - {df.iloc[i]['artist']} (Score: {similarity_scores[i]:.3f})"
        )

        if len(recommendations) == 5:
            break

    return "\n".join(recommendations)

"""Create Gradio Interface"""

app = gr.Interface(
    fn=recommend_song,
    inputs=gr.Textbox(
        label="🎵 Enter Song Name",
        placeholder="Example: Believe"
    ),
    outputs=gr.Textbox(
        label="Recommended Songs",
        lines=10
    ),
    title="🎵 Smart AI Song Recommendation System",
    description="Recommend similar songs using Word2Vec and Cosine Similarity."
)

"""Launch the App"""

app.launch()